### PR TITLE
Update CheckItem structure

### PR DESCRIPTION
**Pull request by aliartiza75**
The PR fixes this issue [link](https://github.com/AntoineAugusti/updown/issues/8)

### CODE REVIEW

**Comment by aliartiza75** [comment]
@AntoineAugusti kindly review this PR.

**Comment by aliartiza75** [comment]
Hi Antoine,

This approach is fine but will cause other users to change their code as you are changing variable type from `bool` to `bool pointer`.

The change that I am suggesting will have less impact. What's your opinion?

**Comment by AntoineAugusti** [comment]
It's better this way. Thanks for drafting a PR

**Comment by aliartiza75** [comment]
@AntoineAugusti  thank you for accepting this PR.

**Pull request merged**
